@host = http://127.0.0.1:5000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjgyNjBmNjdmMDJlZjJkY2NmZGVmZmM5Iiwibmlja25hbWUiOiJtYXN0ZXIwMSIsImV4cCI6MTc0NzQ5MjM0MX0.O8N1uzbvMbfY_YKx2-RC1kEcom9KggkamzH-_eNgPSc
@item_id = 6824678b33b3799bb8c137c3

### 🧑‍💼 회원가입
POST {{host}}/api/users/signup
Content-Type: application/json

{
  "nickname": "test_1",
  "age": 25,
  "gender": "M",
  "address": "Seoul",
  "phone": "01012345678"
}

### 🔐 로그인
POST {{host}}/api/users/login
Content-Type: application/json

{
  "nickname": "master01"
}

### 🔒 인증 확인
GET {{host}}/api/users/protected
Authorization: {{token}}

### 🎁 포인트 적립 (편지 작성)
POST {{host}}/reward/grant
Content-Type: application/json
Authorization: {{token}}

{
  "action": "write_letter"
}

### 🎒 내 아이템 목록
GET {{host}}/item/my
Authorization: {{token}}

### 🎨 아이템 사용
POST {{host}}/item/use
Content-Type: application/json
Authorization: {{token}}

{
  "item_id": "{{item_id}}"
}

### 🧼 아이템 해제
POST {{host}}/item/unuse
Content-Type: application/json
Authorization: {{token}}

{
  "item_id": "{{item_id}}"
}

### 🔍 아이템 상세 조회
GET {{host}}/item/{{item_id}}
Authorization: {{token}}

### 🧾 아이템 카탈로그 조회 (비인증)
GET {{host}}/item/catalog

---

### 💌 편지 전송: 나에게
POST {{host}}/letter/send
Content-Type: application/json
Authorization: {{token}}

{
  "to": "self",
  "content": "시험을 봤는데 시험점수가 너무 낮게 나와서 속상해 기말에 만회해야지지",
  "emotion": "우울"
}

### 💌 편지 전송: 자원봉사자
POST {{host}}/letter/send
Content-Type: application/json
Authorization: {{token}}

{
  "to": "volunteer",
  "content": "힘들 때 위로가 필요해요.",
  "emotion": "슬픔"
}

### 💌 편지 전송: 랜덤
POST {{host}}/letter/send
Content-Type: application/json
Authorization: {{token}}

{
  "to": "random",
  "content": "요즘 가장 크게 느끼는 감정이 무엇인가요?",
  "emotion": "설렘"
}



### 📮 나에게 온 미답장 편지 조회
GET {{host}}/letter/random
Authorization: {{token}}

### 📄 편지 상세 조회
GET {{host}}/letter/682743972fb7d62bf82d36f2
Authorization: {{token}}

### 🤖 AI 질문 옵션 조회
GET {{host}}/letter/reply-options?letter_id={{letter_id}}
Authorization: {{token}}

### ✍️ 답장 보내기
POST {{host}}/letter/reply
Content-Type: application/json
Authorization: {{token}}

{
  "letter_id": "6826aaaaffff000000000013",
  "reply": "당신의 마음을 잘 이해합니다. 힘내세요!"
}

### 📬 내가 받은 답장된 편지 목록
GET {{host}}/letter/replied-to-me
Authorization: {{token}}

### 💬 특정 편지의 댓글 목록
GET {{host}}/letter/for-letter/6826aaaaffff000000000012
Authorization: {{token}}

### 🤖 24시간 경과 자동 답장 트리거
POST {{host}}/letter/auto-reply

### 💾 내가 저장한 편지 목록
GET {{host}}/letter/saved
Authorization: {{token}}

####특정 아이템 조회
GET {{host}}/item/my?category=바다아이템
Authorization: {{token}}
Content-Type: application/json